# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: UTF8
  database: restaurant_development
  host: localhost
  pool: 5
  username: <%= ENV['RESTAURANT_DATABASE_USER'] %>
  password: <%= ENV['RESTAURANT_DATABASE_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: UTF8
  database: restaurant_production
  host: localhost
  pool: 5
  username: <%= ENV['RESTAURANT_DATABASE_USER'] %>
  password: <%= ENV['RESTAURANT_DATABASE_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: UTF8
  database: restaurant_test
  host: localhost
  pool: 5
  username: <%= ENV['RESTAURANT_DATABASE_USER'] %>
  password: <%= ENV['RESTAURANT_DATABASE_PASSWORD'] %>
