# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: UTF8
  database: elevation_cert_d
  host: localhost
  pool: 5
  username: postgres
  password: Akira123!

production:
  adapter: postgresql
  encoding: UTF8
  database: elevation_cert_p
  host: localhost
  pool: 5
  username: postgres
  password: Akira123!
